package UI.Panel;

import java.util.List;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

import product.*;

/**
 *
 * @author Admin
 */
public class AddProduct extends javax.swing.JPanel {

    ProductRepository productrepo = new ProductRepository();
    List<Product> catalog = productrepo.getAllProducts();

    /**
     * Creates new form AddProduct
     */
    public AddProduct() {
        initComponents();
        setupComboBox();
        showProductsByCategory(Catalog.TEA); // ตั้งค่าเริ่มต้น
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1604, 1049));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1604, 1049));
        jPanel1.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                jPanel1.requestFocusInWindow(); // ให้ panel รับ focus → TextField หลุด focus
            }
        });

        jLabel1.setFont(new java.awt.Font("TH Niramit AS", 1, 60)); // NOI18N
        jLabel1.setText("Add Product");

        jLabel2.setFont(new java.awt.Font("TH Niramit AS", 3, 18)); // NOI18N
        jLabel2.setText("Choose Catalog :");

        jLabel3.setFont(new java.awt.Font("TH Niramit AS", 3, 18)); // NOI18N
        jLabel3.setText("Product Name :");

        jTextField1.setFont(new java.awt.Font("TH Niramit AS", 1, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setText("ProductName");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("TH Niramit AS", 3, 18)); // NOI18N
        jLabel4.setText("Product Price :");

        jTextField2.setFont(new java.awt.Font("TH Niramit AS", 1, 36)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2.setText("ProductPrice");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 189, 89));
        jButton1.setFont(new java.awt.Font("TH Niramit AS", 1, 48)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        jPanel2.setBackground(Color.white);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(686, 686, 686)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2))
                        .addGap(170, 170, 170)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(677, 677, 677)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String productName = jTextField1.getText();
        double price = 0.0;
        try {
            price = Double.parseDouble(jTextField2.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "กรุณากรอกราคาที่เป็นตัวเลขเท่านั้น");
            return;
        }

        Catalog selectedCatalog = (Catalog) jComboBox1.getSelectedItem();

        // สร้างรหัสอัตโนมัติ
        ProductRepository productRepo = new ProductRepository();
        productRepo.loadFromFile();
        String newID = productRepo.generateProductID(selectedCatalog);

        // สร้างสินค้าใหม่
        Product newProduct = new Product(newID, productName, price, selectedCatalog);

        // เพิ่มลง repo
        productRepo.AddProduct(newProduct);
        productRepo.saveToFile();

        JOptionPane.showMessageDialog(this, "เพิ่มสินค้าเรียบร้อย: " + newProduct.getProductID());
    }        
    
    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {                                         
        if (jTextField1.getText().equals("ProductName")) {
            jTextField1.setText(""); // ลบข้อความเมื่อโฟกัส
        }
    }                                        

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {                                       
        if (jTextField1.getText().isEmpty()) {
            jTextField1.setText("ProductName"); // กลับมาเป็นข้อความเริ่มต้นถ้าว่าง
        }
    }

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {                                         
        if (jTextField2.getText().equals("ProductPrice")) {
            jTextField2.setText(""); // ลบข้อความเมื่อโฟกัส
        }
    }                                        

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {                                       
        if (jTextField2.getText().isEmpty()) {
            jTextField2.setText("ProductPrice"); // กลับมาเป็นข้อความเริ่มต้นถ้าว่าง
        }
    }


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Catalog> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration          
    
    private void setupComboBox() {
        jComboBox1.setFont(new java.awt.Font("TH Niramit AS", 1, 36)); // NOI18
        jComboBox1.setBackground(Color.white);
        jComboBox1.setModel(new DefaultComboBoxModel<>(Catalog.values()));
        jComboBox1.addActionListener(e -> {
            Catalog selectedCategory = (Catalog) jComboBox1.getSelectedItem();
            showProductsByCategory(selectedCategory);
        });
    }

    // 🔹 ฟังก์ชันนี้จะแสดงสินค้าเฉพาะหมวด
    private void showProductsByCategory(Catalog selectedCategory) {
        // เคลียร์ของเก่าออกก่อน
        jPanel2.removeAll();
        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));

        // ดึงสินค้าทั้งหมดจาก catalog (สมมติว่ามี ProductRepository)
        ProductRepository productRepo = new ProductRepository();
        List<Product> allProducts = productRepo.getAllProducts();

        for (Product p : allProducts) {
            if (p.getCatalog() == selectedCategory) {
                JPanel itemPanel = new JPanel(new BorderLayout());
                itemPanel.setMaximumSize(new Dimension(480, 40));

                JLabel idLabel = new JLabel(p.getProductID() + "  ");
                JLabel nameLabel = new JLabel(p.getProductName() + "  ");
                JLabel priceLabel = new JLabel(String.format("%.2f ฿", p.getPrice()));

                itemPanel.add(idLabel, BorderLayout.WEST);
                itemPanel.add(nameLabel, BorderLayout.CENTER);
                itemPanel.add(priceLabel, BorderLayout.EAST);
                itemPanel.setBackground(Color.white);

                jPanel2.add(itemPanel);
            }
        }

        jPanel2.revalidate();
        jPanel2.repaint();
    }
}

