package UI.Panel;

import java.awt.*;
import java.awt.event.*;
import java.util.List;
import javax.swing.*;

import User.*;

/**
 *
 * @author Admin
 */
public class ChangePassword extends javax.swing.JPanel {

    UserRepository userRepo = new UserRepository();
    AuthService authService = new AuthService(userRepo);    

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword(AuthService authService) {
        this.authService = authService;
        initComponents();
        createUserButtons();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        UserRepository userRepo = new UserRepository();
        List<User> users = userRepo.getAllUsers();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1604, 1049));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1604, 1049));
        jPanel1.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                jPanel1.requestFocusInWindow(); // ให้ panel รับ focus → TextField หลุด focus
            }
        });

        jLabel1.setFont(new java.awt.Font("TH Niramit AS", 1, 60)); // NOI18N
        jLabel1.setText("Change Password");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);


        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        int Height = users.size();
        Height = Height * 50 ;
        jPanel2.setPreferredSize(new java.awt.Dimension(785,Height));
        jPanel2.setLayout(new java.awt.GridLayout());
        jScrollPane1.setViewportView(jPanel2);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);


        jLabel2.setFont(new java.awt.Font("TH Niramit AS", 3, 18)); // NOI18N
        jLabel2.setText("User ID :");

        jTextField1.setFont(new java.awt.Font("TH Niramit AS", 0, 36)); // NOI18N
        jTextField1.setText("UserID");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("TH Niramit AS", 3, 18)); // NOI18N
        jLabel3.setText("Old Password :");

        jLabel4.setFont(new java.awt.Font("TH Niramit AS", 3, 18)); // NOI18N
        jLabel4.setText("New Password :");

        JPopupMenu numpadPopup1 = new JPopupMenu();
        numpadPopup1.setFocusable(false);

        JPanel numpadPanel = createNumpad(jPasswordField1, () -> numpadPopup1.setVisible(false));
        numpadPanel.setPreferredSize(new Dimension(200, 200)); // กำหนดขนาดแน่นอน
        numpadPopup1.add(numpadPanel);

        jPasswordField1.setEchoChar('●');
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPasswordField1.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                numpadPopup1.show(jPasswordField1, jPasswordField1.getWidth(), 0);
            }
        });

        JPopupMenu numpadPopup2 = new JPopupMenu();
        numpadPopup2.setFocusable(false);

        JPanel numpadPanel2 = createNumpad(jPasswordField2, () -> numpadPopup2.setVisible(false));
        numpadPanel2.setPreferredSize(new Dimension(200, 200)); // กำหนดขนาดแน่นอน
        numpadPopup2.add(numpadPanel2);

        jPasswordField2.setEchoChar('●');
        jPasswordField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPasswordField2.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                numpadPopup2.show(jPasswordField2, jPasswordField2.getWidth(), 0);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 189, 89));
        jButton1.setFont(new java.awt.Font("TH Niramit AS", 1, 48)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(632, 632, 632))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(677, 677, 677)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String userID = jTextField1.getText().trim();
        String oldPassword = new String(jPasswordField1.getPassword());
        String newPassword = new String(jPasswordField2.getPassword());

        if(userID.isEmpty() || oldPassword.isEmpty() || newPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "กรุณากรอกข้อมูลให้ครบ", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        UserRepository userRepo = new UserRepository();
        userRepo.loadFromFile(); // โหลดข้อมูลผู้ใช้ล่าสุด

        // ตรวจสอบรหัสผ่านเก่า
        if(authService.verifyPassword(userID, oldPassword)) {
            boolean changed = authService.changePassword(userID, newPassword);
            if(changed) {
                JOptionPane.showMessageDialog(this, "เปลี่ยนรหัสผ่านเรียบร้อยแล้ว", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "ไม่สามารถเปลี่ยนรหัสผ่านได้", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "รหัสผ่านเก่าไม่ถูกต้อง", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // เคลียร์ PasswordField
        jPasswordField1.setText("");
        jPasswordField2.setText("");
    }    
    
    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {                                         
        if (jTextField1.getText().equals("UserID")) {
            jTextField1.setText(""); // ลบข้อความเมื่อโฟกัส
        }
    }                                        

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {                                       
        if (jTextField1.getText().isEmpty()) {
            jTextField1.setText("UserID"); // กลับมาเป็นข้อความเริ่มต้นถ้าว่าง
        }
    }                  


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration     
    
    public void createUserButtons() {
        UserRepository userRepo = new UserRepository();
        List<User> users = userRepo.getAllUsers();  

        // ลบปุ่มเก่าก่อน (ถ้ามี)
        jPanel2.removeAll();

        // ตั้ง layout ให้ panelUsers
        jPanel2.setLayout(new GridLayout(users.size(), 1, 0, 0));
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(0, 0, 0, 0); // spacing
        gbc.gridx = 0;
        gbc.gridy = 0;
        //gbc.anchor = GridBagConstraints.NORTHWEST; // อยู่มุมบนซ้าย
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.weightx = 0.0;  // ขยายเต็มแนวนอน

        int columns = 1;

        int i = 1;
        for (User u : users) {
            
            JButton userButton = new JButton("User " + i + " : " + u.getUserID() + " ("+u.getUserName() + ")");
            userButton.setFont(new java.awt.Font("TH Niramit AS", 1, 24)); // NOI18N
            userButton.setHorizontalAlignment(SwingConstants.LEFT);  // แนวนอน
            userButton.setBackground(Color.white);

            userButton.setFocusPainted(false);  // ปิดเส้นขอบโฟกัส
            userButton.setContentAreaFilled(true); // เปิดการระบายสีเต็มพื้นที่
            userButton.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            userButton.setOpaque(true);
            userButton.setBorderPainted(true);
            i++;

            int buttonHeight = 50;
            int buttonWidth = 400;
            userButton.setPreferredSize(new Dimension(buttonWidth, buttonHeight));
            userButton.setMinimumSize(new Dimension(buttonWidth, buttonHeight));
            userButton.setMaximumSize(new Dimension(buttonWidth, buttonHeight));

            // ActionListener ของแต่ละปุ่ม
            userButton.addActionListener((ActionListener) new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    jTextField1.setText(u.getUserID());
                }
            });

            
            gbc.gridx++;
            if (gbc.gridx == columns) {
                gbc.gridx = 0;
                gbc.gridy++;
            }
            jPanel2.add(userButton, gbc);
            jPanel2.add(Box.createVerticalGlue(), gbc);
        }

        // รีเฟรช panel
        jPanel2.revalidate();
        jPanel2.repaint();
    }

    public static JPanel createNumpad(JTextField textField , Runnable closeAction) {
        JPanel panel = new JPanel(new GridLayout(4,3,0,0)); // 4 แถว 3 คอลัมน์
        String[] buttons = {
            "1","2","3",
            "4","5","6",
            "7","8","9",
            "Del","0","Enter"
        };

        for (String s : buttons) {
            JButton button = new JButton(s);
            button.setFont(new Font("Segoe UI", 1, 15));
            button.setPreferredSize(new Dimension(50, 40));
            button.addActionListener(e -> {
                switch(s) {
                    case "Del":
                        String current = textField.getText();
                        if (!current.isEmpty()) {
                            textField.setText(current.substring(0, current.length() - 1));
                        }
                        break;
                    case "Enter":
                        if (closeAction != null) {
                            closeAction.run(); // เรียก Runnable ปิด popup
                        }
                        break;
                    default: // 0-9
                        if ("Password".equals(textField.getText())) {
                            textField.setText(""); // ล้าง Password ก่อน
                        }
                        textField.setText(textField.getText() + s);
                        break;
                }
            });
            panel.add(button);
        }
        panel.setPreferredSize(new Dimension(300, 170));

        return panel;
    }

    public JPanel getPanelUsers() {
        return jPanel2;
    }
}
