package UI.Panel;

import java.awt.event.*;
import java.awt.*;
import javax.swing.*;

import java.util.List;

import product.*;


/**
 *
 * @author Admin
 */
public class RemoveProduct extends javax.swing.JPanel {

    private ProductRepository productRepo;

    /**
     * Creates new form RemoveProduct
     */
    public RemoveProduct() {
        
        initComponents();

        productRepo = new ProductRepository();
        productRepo.loadFromFile(); // โหลดสินค้าจาก CSV

        // 🔹 ตั้งค่า ComboBox เป็น enum Catalog
        jComboBox1.setModel(new DefaultComboBoxModel<>(Catalog.values()));
        jComboBox1.setFont(new java.awt.Font("TH Niramit AS", 1, 36));
        jComboBox1.setBackground(Color.WHITE);

        // 🔹 เรียกแสดงสินค้าของหมวดแรกทันที
        Catalog firstCategory = (Catalog) jComboBox1.getItemAt(0);
        showProductsByCategory(firstCategory);

        // 🔹 ผูก ActionListener ให้ ComboBox เปลี่ยนหมวด
        jComboBox1.addActionListener(e -> {
            Catalog selectedCategory = (Catalog) jComboBox1.getSelectedItem();
            showProductsByCategory(selectedCategory);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1604, 1049));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1604, 1049));
        jPanel1.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                jPanel1.requestFocusInWindow(); // ให้ panel รับ focus → TextField หลุด focus
            }
        });

        jLabel1.setFont(new java.awt.Font("TH Niramit AS", 1, 60)); // NOI18N
        jLabel1.setText("Remove Product");

        jLabel2.setFont(new java.awt.Font("TH Niramit AS", 3, 18)); // NOI18N
        jLabel2.setText("Choose Catalog :");

        jTextField1.setFont(new java.awt.Font("TH Niramit AS", 1, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setText("ProductID");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("TH Niramit AS", 3, 18)); // NOI18N
        jLabel3.setText("Product ID :");

        jButton1.setBackground(new java.awt.Color(255, 189, 89));
        jButton1.setFont(new java.awt.Font("TH Niramit AS", 1, 48)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        jPanel2.setBackground(Color.white);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(648, 648, 648)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(677, 677, 677)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(197, 197, 197)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(92, 92, 92)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {                                         
        if (jTextField1.getText().equals("ProductID")) {
            jTextField1.setText(""); // ลบข้อความเมื่อโฟกัส
        }
    }                                        

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {                                       
        if (jTextField1.getText().isEmpty()) {
            jTextField1.setText("ProductID"); // กลับมาเป็นข้อความเริ่มต้นถ้าว่าง
        }
    }                                         

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Confirm
        String productID = jTextField1.getText().trim();
    
        if (productID.isEmpty() || productID.equals("ProductID")) {
            JOptionPane.showMessageDialog(this, "กรุณาใส่ ProductID ที่ต้องการลบ", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else{
            // ลบสินค้า
            productRepo.RemoveProductByID(productID);
        
            // บันทึกลงไฟล์
            productRepo.saveToFile();

            // รีเฟรช panel ให้แสดงสินค้าตามหมวดปัจจุบัน
            Catalog selectedCategory = (Catalog) jComboBox1.getSelectedItem();
            showProductsByCategory(selectedCategory);

            JOptionPane.showMessageDialog(this, "ลบสินค้าสำเร็จ", "Success", JOptionPane.INFORMATION_MESSAGE);
        }

        // ล้าง TextField
        jTextField1.setText("");
    }                                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Catalog> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration         
    
    private void showProductsByCategory(Catalog selectedCategory) {
        jPanel2.removeAll();
        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));

        List<Product> allProducts = productRepo.getAllProducts();

        for (Product p : allProducts) {
            if (p.getCatalog() == selectedCategory) {
                JButton productButton = new JButton(
                    p.getProductID() + " - " + p.getProductName() + "  " + String.format("%.2f ฿", p.getPrice())
                );
                productButton.setMaximumSize(new Dimension(499, 40));
                productButton.setAlignmentX(Component.LEFT_ALIGNMENT);
                productButton.setBackground(Color.WHITE);
                productButton.setFocusPainted(false);
                productButton.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));

                // เมื่อกดปุ่ม → set ProductID
                productButton.addActionListener(e -> jTextField1.setText(p.getProductID()));

                jPanel2.add(productButton);
                jPanel2.add(Box.createRigidArea(new Dimension(0, 0)));
            }
        }

        jPanel2.revalidate();
        jPanel2.repaint();
    }
}

