package UI.Panel;

import java.awt.CardLayout;
import java.awt.Font;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.GroupLayout;

import UI.Panel.ProductS.MilkLayout;
import UI.Panel.ProductS.TeaLayout;

public class Summary extends javax.swing.JPanel{
    
    private JPanel contentPanel;

    /**
     * Creates new form Summary
     */
    public Summary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelSummary = new javax.swing.JLabel();
        jLabelSaleSummary = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        contentPanel = new JPanel(new CardLayout());
        contentPanel.setPreferredSize(new java.awt.Dimension(1604, 900));

        // เพิ่ม TeaLayout เข้าไปใน contentPanel
        TeaLayout teaLayout = new TeaLayout();
        contentPanel.add(teaLayout, "Tea");

        MilkLayout milkLayout = new MilkLayout();
        contentPanel.add(milkLayout,"Milk");


        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1604, 1049));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1604, 1049));

        jLabelSummary.setFont(new java.awt.Font("TH Niramit AS", 1, 60)); // NOI18N
        jLabelSummary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSummary.setText("Summary");

        jLabelSaleSummary.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jLabelSaleSummary.setText("Sale Summary");
        jLabelSaleSummary.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel2.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jLabel2.setText("Date :");

        jLabel3.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jLabel3.setText("Time :");

        jLabel4.setFont(new java.awt.Font("TH Niramit AS", 1, 18)); // NOI18N
        jLabel4.setText("-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel6.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jLabel6.setText("Product(size)");

        jList1.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Tea", "Milk", "Coffee", "Juice", "Soda", "Water" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel7.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jLabel7.setText("Quantity");

        jLabel8.setFont(new java.awt.Font("TH Niramit AS", 0, 18)); // NOI18N
        jLabel8.setText("price summary");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            // ส่วนหัวเดิม
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 1610, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSaleSummary)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6)
                        .addGap(497, 497, 497)
                        .addComponent(jLabel7)
                        .addGap(393, 393, 393)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    // ✅ เพิ่ม contentPanel
    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1604, Short.MAX_VALUE)
);

        jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabelSummary)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabelSaleSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(jLabel7)
                .addComponent(jLabel8))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            // ✅ เพิ่ม contentPanel
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addContainerGap()
    )
    );


        add(jPanel1, java.awt.BorderLayout.CENTER);

        jList1.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                String selected = jList1.getSelectedValue();
                CardLayout cl = (CardLayout) (contentPanel.getLayout());

                if ("Tea".equals(selected)) {
                    cl.show(contentPanel, "Tea");
                }
                else if ("Milk".equals(selected)) {
                    cl.show(contentPanel, "Milk");
                }
                // ถ้ามีหน้าอื่น ๆ เพิ่มได้เช่น
                // else if ("Coffee".equals(selected)) { cl.show(contentPanel, "Coffee"); }
            }
        });

    }// </editor-fold>             
    
    
    

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelSaleSummary;
    private javax.swing.JLabel jLabelSummary;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   




}