package UI.Dialog;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

import javax.swing.*;
import java.awt.*;

import ShoppingCart.*;
import User.*;

/**
 *
 * @author Admin
 */
public class Bill extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Bill.class.getName());
    UserRepository userRepo = new UserRepository();
    AuthService authService = new AuthService(userRepo);
    List<CartItem> items;
    double finalPrice;
    double change;
    double amount;

    /**
     * Creates new form Bill
     */
    public Bill(java.awt.Frame parent, boolean modal, AuthService authService, List<CartItem> items, double finalPrice , double change , double amount) {
        super(parent, modal);
        this.authService = authService;
        this.items = items;
        this.finalPrice = finalPrice;
        this.change = change;
        this.amount = amount;
        initComponents();

        saveToCSV(); // ✅ บันทึกข้อมูลสินค้าในไฟล์ Summary.csv


       // new javax.swing.Timer(3000, e -> dispose()).start();
        setLocationRelativeTo(parent); // ให้ dialog อยู่กลาง parent
        setVisible(true);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 400));

        jLabel1.setFont(new java.awt.Font("TH Niramit AS", 3, 28)); // NOI18N
        jLabel1.setText("Simple POS");

        jLabel2.setFont(new java.awt.Font("TH Niramit AS", 1, 18)); // NOI18N
        jLabel2.setText("Product :");

        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");

        jLabel3.setFont(new java.awt.Font("TH Niramit AS", 1, 18)); // NOI18N
        jLabel3.setText("Time : " + now.format(timeFormatter));

        jLabel4.setFont(new java.awt.Font("TH Niramit AS", 1, 18)); // NOI18N
        jLabel4.setText("Date : " + now.format(dateFormatter));

        User current = authService.getCurrentUser();
        String UserID = (current != null) ? current.getUserID() : "Guest";
        String UserName = (current != null) ? current.getUserName() : "Guest";
        jLabel5.setFont(new java.awt.Font("TH Niramit AS", 1, 18)); // NOI18N
        jLabel5.setText("User : "+UserID + " (" + UserName + ")");

        jLabel6.setFont(new java.awt.Font("TH Niramit AS", 1, 14)); // NOI18N
        jLabel6.setText("-+------------------------------------------------------+-");

        jLabel7.setFont(new java.awt.Font("TH Niramit AS", 1, 14)); // NOI18N
        jLabel7.setText("-+------------------------------------------------------+-");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.removeAll();
        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));
        int itemHeight = 30;
        int panelWidth = 280;
        for (CartItem item : items) {
            System.out.println(item);
            JLabel productLabel = new JLabel("  "+item.getProduct().getProductName()
                    + " (" + item.getSize() + ")"
                    + " x " + item.getQuantity()
                    + " = " + String.format("%.2f ฿", Pricing.calculateItemPrice(item))
            );
            productLabel.setFont(new Font("TH Niramit AS", Font.PLAIN, 16));
            productLabel.setPreferredSize(new Dimension(panelWidth, itemHeight));
            productLabel.setMaximumSize(new Dimension(panelWidth, itemHeight));
            productLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
            jPanel2.add(productLabel);
        }
        int panelHeight = items.size() * itemHeight;
        jPanel2.setPreferredSize(new Dimension(panelWidth, panelHeight));
        jPanel2.setMaximumSize(new Dimension(panelWidth, panelHeight));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 430 + panelHeight));
        setPreferredSize(new java.awt.Dimension(350, 430 + panelHeight));
        jPanel2.revalidate();
        jPanel2.repaint();

        jLabel8.setFont(new java.awt.Font("TH Niramit AS", 1, 24)); // NOI18N
        jLabel8.setText("Total :");

        jLabel9.setFont(new java.awt.Font("TH Niramit AS", 1, 24)); // NOI18N
        jLabel9.setText(String.format("%.2f ฿", finalPrice));

        jLabel13.setFont(new java.awt.Font("TH Niramit AS", 1, 20)); // NOI18N
        jLabel13.setText("Amount :");

        jLabel14.setFont(new java.awt.Font("TH Niramit AS", 1, 20)); // NOI18N
        jLabel14.setText("Change :");

        jLabel15.setFont(new java.awt.Font("TH Niramit AS", 1, 20)); // NOI18N
        jLabel15.setText(String.format("%.2f ฿", amount));

        jLabel16.setFont(new java.awt.Font("TH Niramit AS", 1, 20)); // NOI18N
        jLabel16.setText(String.format("%.2f ฿", change));

        jLabel10.setFont(new java.awt.Font("TH Niramit AS", 1, 14)); // NOI18N
        jLabel10.setText("-+------------------------------------------------------+-");

        jLabel11.setFont(new java.awt.Font("TH Niramit AS", 1, 18)); // NOI18N
        jLabel11.setText("<html>Address : 999/1 , Phra Pathom Chedi Subdistrict, <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Mueang Nakhon Pathom District, <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nakhon Pathom Province 73000</html>");

        jLabel12.setFont(new java.awt.Font("TH Niramit AS", 3, 28)); // NOI18N
        jLabel12.setText("Thank You");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(131, 131, 131)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel5))
                        .addComponent(jLabel6)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(6, 6, Short.MAX_VALUE)
                                            .addComponent(jLabel16))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(jLabel15)))))
                                    .addGap(9, 9, 9))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        


        pack();
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration     
    
    private void saveToCSV() {
    String fileName = "./File & Image/Summary.csv";
    java.io.File file = new java.io.File(fileName);

    // ⏱ เวลาและวันที่ปัจจุบัน
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");
        String dateStr = now.format(dateFormatter);
        String timeStr = now.format(timeFormatter);

    // 🔽 ตรงนี้แหละที่ใช้ new java.io.FileWriter(file, true)
    try (java.io.FileWriter writer = new java.io.FileWriter(file, false)) {
        // ถ้าไฟล์ยังไม่มี ให้เขียน header ก่อน
        if (file.length() == 0) {
            writer.write("Date,Time,Product,Size,Quantity,TotalPrice\n");
        }

        // เขียนข้อมูลสินค้าแต่ละรายการ
        for (CartItem item : items) {
            double totalItemPrice = Pricing.calculateItemPrice(item);
            writer.write(String.format("%s,%s,%s,%s,%d,%.2f\n",
                    dateStr,
                    timeStr,
                    item.getProduct().getProductName(),
                    item.getSize(),
                    item.getQuantity(),
                    totalItemPrice
            ));
        }

        writer.flush();
        System.out.println("✅ บันทึกข้อมูลลงไฟล์ Summary.csv แล้ว: " + file.getAbsolutePath());
    } catch (Exception e) {
        e.printStackTrace();
        logger.warning("❌ ไม่สามารถบันทึกไฟล์ Summary.csv ได้: " + e.getMessage());
    }
}

    
}

