package UI.Dialog;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

import ShoppingCart.*;
import product.*;

/**
 *
 * @author Admin
 */
public class SelectSize extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SelectSize.class.getName());
    private final Color defaultColor = new Color(255, 255, 255); // หรือใช้ getBackground() ของ panel
    private final Color selectedColor = new Color(100, 100, 100); // สีปุ่มที่ถูกเลือก

    private JButton selectedSizeButton = null; // เก็บปุ่มที่ถูกเลือก
    private Product product;
    private Size selectedSize = null;   // Normal / Large / Largest
    private int quantity = 1;         // จำนวนเริ่มต้น      

    private static boolean isDefaultQuantity = true;

    /**
     * Creates new form SelectSize
     */
    public SelectSize(java.awt.Frame parent, boolean modal , Product product) {
        super(parent, modal);
        this.product = product;
        initComponents();
        selectedSizeButton = jButton1; // สมมติ jButton1 = Normal
        selectedSize = Size.NORMAL;
        selectButton(selectedSizeButton);

        setLocationRelativeTo(parent); // ให้ dialog อยู่กลาง parent
        //setVisible(true);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(750, 400));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(247, 218, 173));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 400));
        jPanel1.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                jPanel1.requestFocusInWindow(); // ให้ panel รับ focus → TextField หลุด focus
            }
        });

        jLabel1.setFont(new java.awt.Font("TH Niramit AS", 1, 48)); // NOI18N
        jLabel1.setText("Product : "+ product.getProductName() + " - " + product.getPrice() + "฿");

        jButton1.setFont(new java.awt.Font("TH Niramit AS", 1, 36)); // NOI18N
        jButton1.setText("Normal");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("TH Niramit AS", 1, 36)); // NOI18N
        jButton2.setText("Large");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton2.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("TH Niramit AS", 1, 36)); // NOI18N
        jButton3.setText("Largest");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton3.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("TH Niramit AS", 1, 36)); // NOI18N
        jButton4.setText("+");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton4.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        
        jButton5.setFont(new java.awt.Font("TH Niramit AS", 1, 36)); // NOI18N
        jButton5.setText("-");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton5.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });


        jLabel2.setFont(new java.awt.Font("TH Niramit AS", 3, 24)); // NOI18N
        jLabel2.setText("+ 10 Baht");
        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("TH Niramit AS", 3, 24)); // NOI18N
        jLabel3.setText("+ 0 Baht");
        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("TH Niramit AS", 3, 24)); // NOI18N
        jLabel4.setText("+ 20 Baht");
        jLabel4.setHorizontalAlignment(SwingConstants.CENTER);

        jButton4.setBackground(new java.awt.Color(102, 255, 102));
        jButton4.setFont(new java.awt.Font("TH Niramit AS", 1, 48)); // NOI18N
        jButton4.setText("Confirm");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton4.setPreferredSize(new java.awt.Dimension(180, 60));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("TH Niramit AS", 1, 36)); // NOI18N
        jLabel5.setText("Quantity : ");

        JPopupMenu numpadPopup = new JPopupMenu();
        numpadPopup.setFocusable(false);

        JPanel numpadPanel = createNumpad(jTextField1, () -> numpadPopup.setVisible(false));
        numpadPanel.setPreferredSize(new Dimension(220, 200)); // กำหนดขนาดแน่นอน
        numpadPopup.add(numpadPanel);

        // แสดง popup ด้านซ้ายของ textField
        jTextField1.setFont(new java.awt.Font("TH Niramit AS", 0, 36)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText(Integer.toString(quantity));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                numpadPopup.show(jTextField1, jTextField1.getWidth(), 0);
            }

            @Override
            public void focusLost(FocusEvent e) {
                numpadPopup.setVisible(false);
                if (jTextField1.getText().isEmpty()) {
                    jTextField1.setText("1");
                    isDefaultQuantity = true; // คืนค่า flag
                }
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 0, 51));
        jButton5.setFont(new java.awt.Font("TH Niramit AS", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("×");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 539, Short.MAX_VALUE)
                                .addComponent(jButton5)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(37, 37, 37)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {  
        selectedSize = Size.NORMAL; 
        selectSize(jButton1);                                   
        selectButton(jButton1);
    }  

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        selectedSize = Size.LARGE;
        selectSize(jButton2);
        selectButton(jButton2);
    }  

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        selectedSize = Size.LARGEST;
        selectSize(jButton3);
        selectButton(jButton3);
    }    

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Confirm
        int quantity = 1;
        try {
            quantity = Integer.parseInt(jTextField1.getText().trim());
            if (quantity <= 0) {
                JOptionPane.showMessageDialog(this, "จำนวนต้องมากกว่า 0");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "กรุณากรอกจำนวนเป็นตัวเลข");
            return;
        }

        // 2️⃣ ตรวจสอบขนาดที่เลือก
        if (selectedSizeButton == null) {
            JOptionPane.showMessageDialog(this, "กรุณาเลือกขนาดสินค้า");
            return;
        }

        switch (selectedSizeButton.getText()) {
            case "Normal": selectedSize = Size.NORMAL; break;
            case "Large": selectedSize = Size.LARGE; break;
            case "Largest": selectedSize = Size.LARGEST; break;
            default:
                JOptionPane.showMessageDialog(this, "ขนาดสินค้าไม่ถูกต้อง");
                return;
        }

        // 3️⃣ ดึงสินค้า
        if (product == null) {
            JOptionPane.showMessageDialog(this, "สินค้าไม่ถูกต้อง");
            return;
        }

        // 4️⃣ สร้าง CartItem
        CartItem item = new CartItem(product, selectedSize, quantity);

        // 5️⃣ เพิ่มเข้า Cart
        Cart.addItem(item);

        // 6️⃣ ปิด Dialog
        this.dispose();
    }    

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // X
        this.dispose();
    }    

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jButton5;
    // End of variables declaration        
    
    public static JPanel createNumpad(JTextField textField , Runnable closeAction) {
        JPanel panel = new JPanel(new GridLayout(5,3,0,0)); // 4 แถว 3 คอลัมน์
        String[] buttons = {
            "+","-","",
            "1","2","3",
            "4","5","6",
            "7","8","9",
            "Del","0","Enter"
        };

        for (String s : buttons) {
            JButton button = new JButton(s);
            button.setFont(new Font("Segoe UI", 1, 15));
            button.setPreferredSize(new Dimension(50, 40));
            button.addActionListener(e -> {
                switch(s) {
                    case "Del":
                        String current = textField.getText();
                        if (!current.isEmpty()) {
                            textField.setText(current.substring(0, current.length() - 1));
                        }
                        break;
                    case "Enter":
                        if (closeAction != null) {
                            closeAction.run(); // เรียก Runnable ปิด popup
                        }
                        break;
                    case "+" :
                        String current1 = textField.getText();
                        int i = Integer.parseInt(current1);
                        i += 1;
                        String S = Integer.toString(i);
                        textField.setText(S);
                        break;
                    case "-" :
                        String current2 = textField.getText();
                        int ii = Integer.parseInt(current2);
                        if(ii > 1){
                            ii -= 1;
                            String SS = Integer.toString(ii);
                            textField.setText(SS);
                        }
                        break;
                    default: // 0-9
                        if (isDefaultQuantity) {       // ถ้าเป็นค่าเริ่มต้น
                            textField.setText("");     // ล้างค่า
                            isDefaultQuantity = false; // เปลี่ยน flag
                        }
                        textField.setText(textField.getText() + s);
                        break;
                }
            });
            panel.add(button);
        }
        panel.setPreferredSize(new Dimension(300, 170));

        return panel;
    }

    private void selectButton(JButton selectedButton) {
        // รีเซ็ตปุ่มทั้งหมดกลับสีเดิม
        resetButtonColors();

        // ตั้งสีใหม่ให้ปุ่มที่เลือก
        selectedButton.setBackground(selectedColor);
        selectedButton.setOpaque(true);          // บังคับให้แสดง background
        selectedButton.setBorderPainted(true);   // กรณีอยากเห็นขอบด้วย
    }

    // ฟังก์ชันรีเซ็ตสีปุ่ม
    private void resetButtonColors() {
        JButton[] buttons = { jButton1, jButton2, jButton3 };
        for (JButton b : buttons) {
            b.setBackground(defaultColor);
            b.setOpaque(true);          // สำคัญ
            b.setBorderPainted(true);   // สำคัญ
        }
    }

    private void selectSize(JButton button) {
        // เปลี่ยนสีปุ่มที่เลือก
        if (selectedSizeButton != null) {
            selectedSizeButton.setBackground(null); // คืนสีเดิม
        }
        selectedSizeButton = button;
        selectedSizeButton.setBackground(Color.GREEN); // ปุ่มที่เลือกสีเขียว
    }

    public Size getSelectedSize() {
        return selectedSize;
    }

    public int getQuantity() {
        return quantity;
    }
}
