package UI;

import User.*;
import product.*;

import java.awt.*;
import javax.swing.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;

import ShoppingCart.CartItem;
import UI.Dialog.SelectSize;

import java.util.*;
import java.util.List;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class MainUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainUI.class.getName());
    private ProductRepository repo = new ProductRepository();
    AuthService authService;
    UserRepository userRepository;
    private List<CartItem> cart = new ArrayList<>();
    private java.util.List<CartItem> cartItems = new java.util.ArrayList<>();


    /**
     * Creates new form Main
     */
    public MainUI(AuthService authService) {
        this.authService = authService;
        initComponents();

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> setVisible(true));

        /*  กำหนด catalog ทั้งหมด
        Set<String> catalogs = new HashSet<>(Arrays.asList("Tea","soda","juice","milk","coffee","water"));

        // สร้าง JPanel ของสินค้าตาม catalog
        for (String cat : catalogs) {
            JPanel panel = createProductPanelPage(cat , 16); // 16 per page
            containerPanels.put(cat, panel);
        }

        JPanel catalogButtonPanel = new JPanel();
        // สร้างปุ่ม catalog
        createCatalogButtons(catalogButtonPanel, catalogs, jPanel2_1);

        // แสดง catalog แรกเริ่ม
        jPanel2_1.add(containerPanels.get("tea"), BorderLayout.CENTER);
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Time = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel2_1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3_1 = new javax.swing.JPanel();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(255, 145, 77));
        //MainPanel.setPreferredSize(new java.awt.Dimension(1920, 1080));

        pack();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        Time.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        Timer timer = new Timer(1000, e -> {
            LocalDateTime now = LocalDateTime.now();
            Time.setText("Date & Time: " + dtf.format(now));
        });
        timer.start();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 1049));

        jLabel1.setFont(new java.awt.Font("TH Charm of AU", 1, 60)); // NOI18N
        jLabel1.setText("---------------");

        jLabel2.setFont(new java.awt.Font("TH Charm of AU", 1, 60)); // NOI18N
        jLabel2.setText("Category");

        jButton1.setBackground(new java.awt.Color(247, 218, 173));
        jButton1.setFont(new java.awt.Font("TH Niramit AS", 1, 52)); // NOI18N
        jButton1.setText("Tea");
        jButton1.setToolTipText("");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setPreferredSize(new java.awt.Dimension(296, 70));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPanel panel = createProductPanel("TEA"); 
                jPanel2_1.removeAll();  // ล้างปุ่มเก่าออกทั้งหมด
                jPanel2_1.add(panel);
                jPanel2_1.revalidate(); // รีเฟรช layout
                jPanel2_1.repaint(); 
            }
        });

        jButton2.setBackground(new java.awt.Color(247, 218, 173));
        jButton2.setFont(new java.awt.Font("TH Niramit AS", 1, 48)); // NOI18N
        jButton2.setText("Milk");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setPreferredSize(new java.awt.Dimension(296, 70));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPanel panel = createProductPanel("MILK"); 
                jPanel2_1.removeAll();  // ล้างปุ่มเก่าออกทั้งหมด
                jPanel2_1.add(panel);
                jPanel2_1.revalidate(); // รีเฟรช layout
                jPanel2_1.repaint(); 
            }
        });

        jButton3.setBackground(new java.awt.Color(247, 218, 173));
        jButton3.setFont(new java.awt.Font("TH Niramit AS", 1, 48)); // NOI18N
        jButton3.setText("Coffee");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.setPreferredSize(new java.awt.Dimension(296, 70));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPanel panel = createProductPanel("COFFEE"); 
                jPanel2_1.removeAll();  // ล้างปุ่มเก่าออกทั้งหมด
                jPanel2_1.add(panel);
                jPanel2_1.revalidate(); // รีเฟรช layout
                jPanel2_1.repaint(); 
            }
        });

        jButton4.setBackground(new java.awt.Color(247, 218, 173));
        jButton4.setFont(new java.awt.Font("TH Niramit AS", 1, 48)); // NOI18N
        jButton4.setText("Juice");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.setPreferredSize(new java.awt.Dimension(296, 70));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPanel panel = createProductPanel("JUICE"); 
                jPanel2_1.removeAll();  // ล้างปุ่มเก่าออกทั้งหมด
                jPanel2_1.add(panel);
                jPanel2_1.revalidate(); // รีเฟรช layout
                jPanel2_1.repaint(); 
            }
        });

        jButton5.setBackground(new java.awt.Color(247, 218, 173));
        jButton5.setFont(new java.awt.Font("TH Niramit AS", 1, 48)); // NOI18N
        jButton5.setText("Soda");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton5.setPreferredSize(new java.awt.Dimension(296, 70));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPanel panel = createProductPanel("SODA"); 
                jPanel2_1.removeAll();  // ล้างปุ่มเก่าออกทั้งหมด
                jPanel2_1.add(panel);
                jPanel2_1.revalidate(); // รีเฟรช layout
                jPanel2_1.repaint(); 
            }
        });

        jButton6.setBackground(new java.awt.Color(247, 218, 173));
        jButton6.setFont(new java.awt.Font("TH Niramit AS", 1, 48)); // NOI18N
        jButton6.setText("Water");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton6.setPreferredSize(new java.awt.Dimension(296, 70));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPanel panel = createProductPanel("WATER"); 
                jPanel2_1.removeAll();  // ล้างปุ่มเก่าออกทั้งหมด
                jPanel2_1.add(panel);
                jPanel2_1.revalidate(); // รีเฟรช layout
                jPanel2_1.repaint(); 
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)))
                .addGap(2, 2, 2)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(517, Short.MAX_VALUE))
        );

        User current = authService.getCurrentUser();
        String UserID = (current != null) ? current.getUserID() : "Guest";
        String UserName = (current != null) ? current.getUserName() : "Guest";
        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setText("User : "+UserID + " (" + UserName + ")");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setText("Setting");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setText("Logout");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setPreferredSize(new java.awt.Dimension(810, 206));

        jButton7.setBackground(new java.awt.Color(247, 218, 173));
        jButton7.setFont(new java.awt.Font("TH Niramit AS", 1, 24)); // NOI18N
        jButton7.setText("^");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(247, 218, 173));
        jButton8.setFont(new java.awt.Font("TH Niramit AS", 1, 24)); // NOI18N
        jButton8.setText("v");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jPanel2_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2_1.setPreferredSize(new java.awt.Dimension(795, 950));
        JPanel panel = createProductPanel("TEA"); 
        jPanel2_1.setLayout(new java.awt.GridLayout(1,1));
        jPanel2_1.add(panel, BorderLayout.CENTER);


        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2_1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(247, 218, 173));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel6.setFont(new java.awt.Font("TH Niramit AS", 1, 36)); // NOI18N
        jLabel6.setText("In cart :");

        jButton9.setBackground(new java.awt.Color(255, 189, 89));
        jButton9.setFont(new java.awt.Font("TH Niramit AS", 1, 48)); // NOI18N
        jButton9.setText("Discount");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 49, 49));
        jButton10.setFont(new java.awt.Font("TH Niramit AS", 1, 36)); // NOI18N
        jButton10.setText("Close the bill");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("TH Niramit AS", 1, 36)); // NOI18N
        jLabel7.setText("Price :  ");

        jLabel8.setFont(new java.awt.Font("TH Niramit AS", 1, 36)); // NOI18N
        jLabel8.setText("Quantity : ");

        jLabel9.setFont(new java.awt.Font("TH Niramit AS", 1, 36)); // NOI18N
        jLabel9.setText("Discount : ");

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel3_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel3_1Layout = new javax.swing.GroupLayout(jPanel3_1);
        jPanel3_1.setLayout(jPanel3_1Layout);
        jPanel3_1Layout.setHorizontalGroup(
            jPanel3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
        );
        jPanel3_1Layout.setVerticalGroup(
            jPanel3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 877, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel3_1);

         javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addGap(147, 147, 147)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(144, 144, 144))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(673, 673, 673)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Time)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(711, 711, 711)
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(15, 15, 15))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Time)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1049, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                         

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }              
    
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // Logout
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }                                    

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // Setting
        this.dispose();
    }  

    // Variables declaration - do not modify                     
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel Time;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2_1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jPanel3_1;
    // End of variables declaration  

    public List<Product> getProductsByCatalog(String catalog) {
        List<Product> result = new ArrayList<>();
        repo.loadFromFile();
        for (Product p : repo.getAllProducts()) {   // สมมติ products คือ List<Product> ที่โหลดจาก CSV
            if (p.getCatalog().name().equalsIgnoreCase(catalog)) {
                result.add(p);

            }
        }
        return result;
    }

    // สร้าง JPanel สำหรับหน้าเดียว
    private JPanel createProductPanel(String catalogName) {
        int itemsPerPage = 16; // 2x8 ช่อง
        int page = 0; // หน้าแรก

        // ดึงสินค้าจาก repository ตาม catalog
        List<Product> products = getProductsByCatalog(catalogName);

        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(8, 2, 0, 0)); // 2 แถว 8 คอลัมน์, ช่องว่าง 10px

        int start = page * itemsPerPage;
        int end = Math.min(start + itemsPerPage, products.size());

        for (int i = start; i < end; i++) {
            Product p = products.get(i);

            JButton btn = new JButton("<html>" + p.getProductName() + " (Normal)" + "<br>Price: " + p.getPrice() + "฿</html>");
            btn.setFont(new Font("TH Niramit AS", Font.BOLD, 32));
            btn.setBackground(new Color(255, 255, 255));
            btn.setHorizontalAlignment(SwingConstants.LEFT);
            // เพิ่มระยะห่างจากขอบ (บน, ซ้าย, ล่าง, ขวา)
            btn.setMargin(new Insets(0, 10, 0, 0));
            btn.setFocusable(false);

            // เพิ่ม ActionListener
            btn.addActionListener(e -> {
                SelectSize dialog = new SelectSize(this, true, p); // ส่ง product เข้าไป
                dialog.setLocationRelativeTo(this);
                dialog.setVisible(true); // modal -> รอจนปิด dialog

                // เมื่อปิด dialog, รับค่าจาก dialog
                Size selectedSize = dialog.getSelectedSize();      // ต้องมี getter ใน SelectSize
                int quantity = dialog.getQuantity();               // ต้องมี getter ใน SelectSize

                if (selectedSize != null && quantity > 0) {
                    CartItem item = new CartItem(p, selectedSize, quantity);
                    updateCartPanel();
                    cart.add(item);
                }
            });

            panel.add(btn);
        }

        // เติมช่องว่างถ้าน้อยกว่า 16
        for (int i = end - start; i < itemsPerPage; i++) {
            JButton EmptyB = new JButton();
            EmptyB.setBackground(new Color(255, 255, 255));
            panel.add(EmptyB);
        }
        return panel;
    }

    private void updateCartPanel() {
        // ล้าง panel ก่อน
        jPanel3_1.removeAll();

        // ตั้ง layout ใหม่: BoxLayout แนวตั้ง
        jPanel3_1.setLayout(new BoxLayout(jPanel3_1, BoxLayout.Y_AXIS));

        // วนลูปสินค้าใน cart
        for (CartItem item : cartItems) {
            JPanel itemPanel = new JPanel();
            itemPanel.setLayout(new BorderLayout()); // ให้สามารถวางปุ่ม X ขวาสุด

            // สร้าง label แสดงชื่อ, ขนาด, จำนวน, ราคา
            JLabel itemLabel = new JLabel(
                item.getProduct().getProductName() + " (" + item.getSize() + ") x " + item.getQuantity()
                + " = " + (item.getProduct().getPrice() * item.getQuantity()) + "฿"
            );
            itemLabel.setFont(new Font("TH Niramit AS", Font.PLAIN, 24));
            itemPanel.add(itemLabel, BorderLayout.CENTER);

            // ปุ่มลบ
            JButton removeButton = new JButton("X");
            removeButton.setFont(new Font("TH Niramit AS", Font.BOLD, 18));
            removeButton.setForeground(Color.RED);
            removeButton.setFocusable(false);
            removeButton.addActionListener(e -> {
                cartItems.remove(item);
                updateCartPanel(); // รีเฟรช panel หลังลบ
            });
            itemPanel.add(removeButton, BorderLayout.EAST);

            // เพิ่ม panel สินค้าเข้า jPanel3_1
            jPanel3_1.add(itemPanel);

            // เว้นระยะด้านล่างเล็กน้อย
            jPanel3_1.add(Box.createRigidArea(new Dimension(0, 5)));
        }

        // รีเฟรช UI
        jPanel3_1.revalidate();
        jPanel3_1.repaint();
    }
    
}
